[[languages]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "rust"
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "ruby"
[language-server.solargraph]
config = { diagnostics = true, formatting = true }

# [[language]]
# name = "ruby"
# config = { solargraph = { diagnostics = true, formatting = true } }
# formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal"] }
