
# See https://github.com/rszyma/kanata-tray for help with configuration.
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/v0.1.0/doc/config_schema.json"

general.allow_concurrent_presets = false
defaults.tcp_port = 5829

[defaults.layer_icons]


[presets.'Default Preset']
kanata_executable = '~/dotfiles/kanata/kanata'
kanata_config     = '~/dotfiles/kanata/kanata.kbd'
autorun = true

